### ISSUE TITLE
FCT 2019 changes

### ISSUE THREAD

**Issue by LeonardoViotti** [worldbank/dime-r-training#34]
Consolidating previous issues 

Overall:
- [x] Remove all mentions to master in presentations
- [x] Make sure to note that the spatial data session is an advanced session and requires attendance to previous classes #32 

Intro I:
- [x] Explain how functions takes parameters, ordered parameters, named parameters (header = T) #18
- [x] Explain that functions returns values. explain that returned values can be applied directly to a function, you do not have to store in a local and then use in the next function #18 

Data visualization:
- [x] change to ggsave() always with height/width #32
Descriptive analysis:

Data cleaning:
- [x] Discuss the way R treats missing values #32
- [ ] Instead of write.dta13, maybe use write_dta from the haven package? #32

Descriptive analysis:

- [x] In exercise 3 (stargazers and labels)  #18 
* make it clear that they should go back to the code they just run with stargazer and modify it so that it takes the labels as an argument.
* in the solution, do not use obj rawOutput in the file.path() function, as we have not introduced that object in class

- [x] Slide with example for aggregate():  #18 
* the first slide has outdated syntax
* this exercise is also called exercise 3 as well
* did not catch what it was, but there was some type of typo in by(region)

**Comment by LeonardoViotti** [comment]
Resolved in 7a60597cdfe243834606c7f0b2a21d18225cfcdc
